# Generated by Django 4.2.7 on 2024-01-07 07:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('platform', models.CharField(choices=[('Google Ads', 'Google Ads'), ('Facebook Ads', 'Facebook Ads')], max_length=20)),
                ('campaign_sector', models.CharField(choices=[('Tecnologia', 'Tecnologia'), ('Civil', 'Construção Civil'), ('Consultoria', 'Consultoria')], max_length=30)),
                ('funnel_position', models.CharField(choices=[('TOPO', 'Topo de Funil'), ('MEIO', 'Meio de Funil'), ('FUNDO', 'Fundo de Funil'), ('GERAL', 'Geral')], max_length=10)),
                ('clicks', models.IntegerField()),
                ('conversions', models.IntegerField()),
                ('weekly_cost', models.FloatField()),
                ('notes', models.CharField(default='...', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14)),
                ('birth_date', models.DateField(null=True)),
                ('education', models.CharField(choices=[('Fundamental Completo', 'Ensino Fundamental Completo'), ('Médio Completo', 'Ensino Médio Completo'), ('Superior Completo', 'Ensino Superior Completo')], default='Superior Completo', max_length=25, null=True)),
                ('marital_status', models.CharField(choices=[('Solteiro', 'Solteiro(a)'), ('Casado', 'Casado(a)'), ('Divorciado', 'Divorciado(a)'), ('União Estável', 'União Estável'), ('Outro', 'Outro')], default='Solteiro', max_length=15, null=True)),
                ('income', models.CharField(choices=[('3', 'Até 3 salários mínimos'), ('6', 'Até 6 salários mínimos'), ('9', 'Até 9 salários mínimos'), ('+9', 'Acima de 9 salários mínimos')], max_length=5, null=True)),
                ('funnel_time', models.PositiveIntegerField(default=15)),
                ('notes', models.CharField(default='...', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('Tecnologia', 'Tecnologia'), ('Civil', 'Construção Civil'), ('Consultoria', 'Consultoria')], max_length=15)),
                ('total_value', models.FloatField()),
                ('n_of_services', models.PositiveSmallIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('deadline', models.DateField()),
                ('contract_link', models.CharField(max_length=250)),
                ('notes', models.CharField(default='...', max_length=150)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.client')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('sector', models.CharField(choices=[('Tecnologia', 'Tecnologia'), ('Civil', 'Construção Civil'), ('Consultoria', 'Consultoria')], default='Tecnologia', max_length=15)),
                ('gender', models.CharField(choices=[('Homem', 'Homem'), ('Mulher', 'Mulher')], max_length=10)),
                ('status', models.CharField(choices=[('PRÉ-DIAGNÓSTICO', 'Pré-Diagnóstico'), ('PERDIDO PRÉ-DIAG', 'Perdido Pré-Diagnóstico'), ('PRÉ-PROPOSTA', 'Pré-Proposta'), ('PERDIDO PRÉ-PROP', 'Perdido Pré-Proposta'), ('PÓS-PROPOSTA', 'Pós-Proposta'), ('PERDIDO PÓS-PROP', 'Perdido Pós-Proposta'), ('CONTRATO FECHADO', 'Contrato Fechado')], default='PRÉ-DIAGNÓSTICO', max_length=20)),
                ('source', models.CharField(choices=[('Indicação', 'Indicação'), ('Facebook Ads', 'Facebook Ads'), ('Google Ads', 'Google Ads'), ('Ativa', 'Prospecção Ativa'), ('Passiva', 'Prospecção Passiva')], max_length=20)),
                ('email', models.CharField(max_length=80, null=True)),
                ('phone', models.CharField(default='', max_length=16)),
                ('field_of_action', models.CharField(default='', max_length=30, null=True)),
                ('arrival_date', models.DateField()),
                ('notes', models.CharField(default='...', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('sector', models.CharField(choices=[('Tecnologia', 'Tecnologia'), ('Civil', 'Construção Civil'), ('Comercial', 'Comercial'), ('Recursos Humanos', 'Recursos Humanos'), ('Adm-Fin', 'Adminstrativo Financeiro'), ('Consultoria', 'Consultoria')], max_length=20)),
                ('role', models.CharField(choices=[('Assessor', 'Assessor(a)'), ('Consultor', 'Consultor(a)'), ('Gerente', 'Gerente'), ('Diretor', 'Diretor(a)'), ('Presidente', 'Presidente')], max_length=20)),
                ('date_of_entry', models.DateField()),
                ('date_of_leave', models.DateField(null=True)),
                ('professional_email', models.CharField(max_length=80)),
                ('academic_email', models.CharField(max_length=80, null=True)),
                ('phone', models.CharField(max_length=16)),
                ('cpf', models.CharField(max_length=14)),
                ('rg', models.CharField(max_length=9)),
                ('degree', models.CharField(max_length=50, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('notes', models.CharField(default='...', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(choices=[('Sistema', 'Sistema Web'), ('Website', 'Website'), ('Aplicativo', 'Aplicativo'), ('Landing Page', 'Landing Page'), ('Protótipo', 'Protótipo'), ('E-Commerce', 'E-Commerce'), ('Arquitetônico', 'Proj. Arquitetônico'), ('Hidrossanitário', 'Proj. Hidrossanitário'), ('Elétrico', 'Proj. Elétrico'), ('Captação', 'Proj. de Captação'), ('Incêndio', 'Proj. de Combate à Incêndio'), ('Mapeamento de Processos', 'Mapeamento de Processos'), ('Planejamento Estratégico', 'Planejamento Estratégico'), ('Plano de Negócios', 'Plano de Negócios')], max_length=30)),
                ('consultants', models.PositiveSmallIntegerField()),
                ('estimated_time', models.PositiveSmallIntegerField()),
                ('actual_time', models.PositiveSmallIntegerField(null=True)),
                ('price', models.FloatField()),
                ('notes', models.CharField(max_length=100)),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.contract')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.member')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#000000', max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('network', models.CharField(choices=[('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn'), ('Facebook', 'Facebook'), ('TkTok', 'TikTok')], max_length=15)),
                ('followers', models.PositiveIntegerField()),
                ('impressions', models.PositiveIntegerField()),
                ('reach', models.PositiveIntegerField()),
                ('engagement', models.PositiveIntegerField(null=True)),
                ('notes', models.CharField(default='...', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveSmallIntegerField()),
                ('members', models.ManyToManyField(to='dashboard.member')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.service')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='tags',
            field=models.ManyToManyField(to='dashboard.servicetag'),
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=300)),
                ('notes', models.CharField(default='...', max_length=300)),
                ('lead_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.lead')),
            ],
        ),
        migrations.CreateModel(
            name='PostSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csat', models.CharField(choices=[('Totalmente Satisfeito', 'Totalmente Satisfeito'), ('Satisfeito', 'Satisfeito'), ('Neutro', 'Neutro'), ('Insatisfeito', 'Insatisfeito'), ('Totalmente Insatisfeito', 'Totalmente Insatisfeito')], max_length=30)),
                ('nps', models.PositiveSmallIntegerField()),
                ('treatment', models.PositiveSmallIntegerField()),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.contract')),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='member_id',
            field=models.ForeignKey(limit_choices_to={'sector': 'COM'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.member'),
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('date', models.DateField()),
                ('paid_off', models.BooleanField()),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.IntegerField(null=True)),
                ('authority', models.IntegerField(null=True)),
                ('need', models.IntegerField(null=True)),
                ('timing', models.IntegerField(null=True)),
                ('time_to_respond', models.IntegerField(null=True)),
                ('behavior', models.IntegerField(null=True)),
                ('score', models.CharField(max_length=1)),
                ('estimated_price', models.FloatField()),
                ('notes', models.CharField(default='...', max_length=300)),
                ('lead_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=80)),
                ('cnpj', models.CharField(max_length=18)),
                ('field_of_action', models.CharField(max_length=100)),
                ('annual_revenue', models.FloatField(null=True)),
                ('locations', models.PositiveSmallIntegerField(null=True)),
                ('employees', models.PositiveSmallIntegerField(null=True)),
                ('registration_link', models.CharField(max_length=300, null=True)),
                ('notes', models.CharField(default='...', max_length=150)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='lead_id',
            field=models.ForeignKey(limit_choices_to={'status': 'CONTRATO FECHADO'}, on_delete=django.db.models.deletion.CASCADE, to='dashboard.lead'),
        ),
    ]
