# Generated by Django 4.2.7 on 2023-12-16 18:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignMetric',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('platform', models.CharField(choices=[('GOOGLEADS', 'Google Ads'), ('FBADS', 'Facebook Ads')], max_length=10)),
                ('campaign_sector', models.CharField(choices=[('TEC', 'Tecnologia'), ('CIV', 'Construção Civil'), ('CON', 'Consultoria')], max_length=3)),
                ('funnel_position', models.CharField(choices=[('TOPO', 'Topo de Funil'), ('MEIO', 'Meio de Funil'), ('FUNDO', 'Fundo de Funil'), ('GERAL', 'Geral')], max_length=5)),
                ('clicks', models.IntegerField()),
                ('conversions', models.IntegerField()),
                ('weekly_cost', models.FloatField()),
                ('notes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(default='', max_length=14)),
                ('birth_date', models.DateField(default=datetime.datetime.now)),
                ('education', models.CharField(choices=[('EF-COMPLETO', 'Ensino Fundamental Completo'), ('EM-INCOMPLETO', 'Ensino Médio Incompleto'), ('ES-INCOMPLETO', 'Ensino Superior Incompleto'), ('ES-COMPLETO', 'Ensino Superior Completo')], default='ES-COMPLETO', max_length=15)),
                ('marital_status', models.CharField(choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIÚVO', 'Viúvo(a)'), ('UNIÃO ESTÁVEL', 'União Estável')], default='SOLTEIRO', max_length=15)),
                ('monthly_income', models.CharField(choices=[('1', 'Até 1 salário mínimo'), ('1,5', 'Até 1,5 salários mínimos'), ('6,5', 'Até 6,5 salários mínimos'), ('9', 'Até 9 salários mínimos'), ('+9', 'Acima de 9 salários mínimos')], default='6,5', max_length=5)),
                ('funnel_time', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('TEC', 'Tecnologia'), ('CIV', 'Construção Civil'), ('CON', 'Consultoria')], max_length=3)),
                ('total_value', models.FloatField()),
                ('n_of_services', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('link_of_contract', models.CharField(max_length=150)),
                ('notes', models.CharField(max_length=100)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.client')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=32)),
                ('last_name', models.CharField(default='', max_length=32)),
                ('sector', models.CharField(choices=[('TEC', 'Tecnologia'), ('CIV', 'Construção Civil'), ('CON', 'Consultoria')], default='TEC', max_length=3)),
                ('gender', models.CharField(choices=[('M', 'Homem'), ('F', 'Mulher')], default='', max_length=1)),
                ('status', models.CharField(choices=[('PRÉ-DIAGNÓSTICO', 'Pré-Diagnóstico'), ('PERDIDO PRÉ-DIAG', 'Perdido Pré-Diagnóstico'), ('PRÉ-PROPOSTA', 'Pré-Proposta'), ('PERDIDO PRÉ-PROP', 'Perdido Pré-Proposta'), ('PÓS-PROPOSTA', 'Pós-Proposta'), ('PERDIDO PÓS-PROP', 'Perdido Pós-Proposta'), ('CONTRATO FECHADO', 'Contrato Fechado')], default='PRÉ-DIAGNÓSTICO', max_length=20)),
                ('source', models.CharField(choices=[('INDICAÇÃO', 'Indicação'), ('FBADS', 'Facebook Ads'), ('GOOGLEADS', 'Google Ads'), ('ATIVA', 'Prospecção Ativa'), ('PASSIVA', 'Prospecção Passiva')], default='', max_length=10)),
                ('email', models.CharField(default='', max_length=80)),
                ('phone', models.CharField(default='', max_length=16)),
                ('field_of_action', models.CharField(default='', max_length=30)),
                ('score', models.CharField(max_length=1)),
                ('date', models.DateField()),
                ('notes', models.CharField(default='', max_length=150)),
                ('budget', models.BooleanField()),
                ('authority', models.BooleanField()),
                ('need', models.BooleanField()),
                ('timing', models.BooleanField()),
                ('time_to_respond', models.BooleanField()),
                ('behavior', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('sector', models.CharField(choices=[('TEC', 'Tecnologia'), ('CIV', 'Construção Civil'), ('COM', 'Comercial'), ('RH', 'Recursos Humanos'), ('ADM', 'Adiminstrativo Financeiro')], max_length=3)),
                ('role', models.CharField(choices=[('ASS', 'Assessor(a)'), ('CON', 'Consultor(a)'), ('GER', 'Gerente'), ('DIR', 'Diretor(a)'), ('PRE', 'Presidente')], max_length=3)),
                ('date_of_entry', models.DateField()),
                ('date_of_leave', models.DateField(null=True)),
                ('professional_email', models.CharField(max_length=80)),
                ('academic_email', models.CharField(max_length=80, null=True)),
                ('phone', models.CharField(max_length=16)),
                ('cpf', models.CharField(max_length=14)),
                ('rg', models.CharField(max_length=9, null=True)),
                ('degree', models.CharField(max_length=40)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=300, null=True)),
                ('notes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaMetric',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('network', models.CharField(choices=[('IG', 'Instagram'), ('LI', 'LinkedIn'), ('FC', 'Facebook'), ('TK', 'TikTok')], max_length=2)),
                ('followers', models.PositiveIntegerField()),
                ('impressions', models.PositiveIntegerField()),
                ('reach', models.PositiveIntegerField()),
                ('engagement', models.PositiveIntegerField()),
                ('notes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(choices=[('Sistema', 'Sistema Web'), ('Website', 'Website'), ('Aplicativo', 'Aplicativo'), ('Landing Page', 'Landing Page'), ('Protótipo', 'Protótipo'), ('E-Commerce', 'E-Commerce'), ('Arquitetônico', 'Proj. Arquitetônico'), ('Hidrossanitário', 'Proj. Hidrossanitário'), ('Elétrico', 'Proj. Elétrico'), ('Captação', 'Proj. de Captação'), ('Incêndio', 'Proj. de Combate à Incêndio'), ('Mapeamento', 'Mapeamento de Processos')], max_length=18)),
                ('estimated_time', models.PositiveSmallIntegerField()),
                ('actual_time', models.PositiveSmallIntegerField(null=True)),
                ('n_of_consultants', models.PositiveSmallIntegerField()),
                ('price', models.FloatField()),
                ('notes', models.CharField(max_length=100)),
                ('client_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dashboard.client')),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.contract')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.member')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=80)),
                ('cnpj', models.CharField(max_length=18)),
                ('field_of_action', models.CharField(max_length=100)),
                ('annual_revenue', models.FloatField()),
                ('n_of_locations', models.PositiveSmallIntegerField()),
                ('n_of_employees', models.PositiveSmallIntegerField()),
                ('proof_of_registration_link', models.CharField(max_length=150)),
                ('notes', models.CharField(max_length=100)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='lead_id',
            field=models.ForeignKey(limit_choices_to={'status': 'CONTRATO FECHADO'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.lead'),
        ),
    ]
