# Generated by Django 4.2.7 on 2023-12-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='authority',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lead',
            name='behavior',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lead',
            name='budget',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lead',
            name='need',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lead',
            name='time_to_respond',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lead',
            name='timing',
            field=models.IntegerField(),
        ),
    ]
