# Generated by Django 4.2.7 on 2024-01-07 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='member_id',
            field=models.ForeignKey(limit_choices_to={'sector': 'Comercial'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.member'),
        ),
    ]
