# Generated by Django 4.2.7 on 2024-01-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_lead_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposition',
            name='date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
