# Generated by Django 4.2.7 on 2023-12-17 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_lead_authority_alter_lead_behavior_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='client_id',
        ),
        migrations.AddField(
            model_name='contract',
            name='member_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.member'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaignmetric',
            name='notes',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='education',
            field=models.CharField(choices=[('EF-COMPLETO', 'Ensino Fundamental Completo'), ('EM-INCOMPLETO', 'Ensino Médio Incompleto'), ('ES-INCOMPLETO', 'Ensino Superior Incompleto'), ('ES-COMPLETO', 'Ensino Superior Completo')], default='ES-COMPLETO', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='funnel_time',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='client',
            name='marital_status',
            field=models.CharField(choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIÚVO', 'Viúvo(a)'), ('UNIÃO ESTÁVEL', 'União Estável')], default='SOLTEIRO', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='monthly_income',
            field=models.CharField(choices=[('1', 'Até 1 salário mínimo'), ('1,5', 'Até 1,5 salários mínimos'), ('6,5', 'Até 6,5 salários mínimos'), ('9', 'Até 9 salários mínimos'), ('+9', 'Acima de 9 salários mínimos')], default='6,5', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='annual_revenue',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='n_of_employees',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='n_of_locations',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='notes',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='contract',
            name='link_of_contract',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='contract',
            name='notes',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.CharField(default='', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='field_of_action',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='notes',
            field=models.CharField(default='-', max_length=150),
        ),
        migrations.AlterField(
            model_name='member',
            name='academic_email',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='member',
            name='rg',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='socialmediametric',
            name='notes',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
