# Generated by Django 4.2.7 on 2023-12-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_service_client_id_contract_member_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='monthly_income',
        ),
        migrations.AddField(
            model_name='client',
            name='income',
            field=models.CharField(choices=[('3', 'Até 3 salários mínimos'), ('6', 'Até 6 salários mínimos'), ('9', 'Até 9 salários mínimos'), ('+9', 'Acima de 9 salários mínimos')], default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='education',
            field=models.CharField(choices=[('EF-COMPLETO', 'Ensino Fundamental Completo'), ('EM-COMPLETO', 'Ensino Médio Completo'), ('ES-COMPLETO', 'Ensino Superior Completo')], default='ES-COMPLETO', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='marital_status',
            field=models.CharField(choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('UNIÃO ESTÁVEL', 'União Estável'), ('OUTRO', 'Outro')], default='SOLTEIRO', max_length=15, null=True),
        ),
    ]
