# Generated by Django 4.2.7 on 2024-01-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_diagnostic_date_proposition_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmediametric",
            name="network",
            field=models.CharField(
                choices=[
                    ("Instagram", "Instagram"),
                    ("LinkedIn", "LinkedIn"),
                    ("Facebook", "Facebook"),
                    ("TikTok", "TikTok"),
                ],
                max_length=15,
            ),
        ),
    ]
