# Generated by Django 4.2.7 on 2024-01-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_remove_campaignmetric_funnel_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="notes",
            field=models.CharField(default="...", max_length=300),
        ),
    ]
