# Generated by Django 4.2.7 on 2024-02-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0006_alter_lead_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="contract_link",
            field=models.CharField(max_length=300),
        ),
    ]
