# Generated by Django 4.2.7 on 2024-02-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0007_alter_contract_contract_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="project",
            field=models.CharField(max_length=40),
        ),
    ]
