# Generated by Django 4.2.7 on 2024-02-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0008_alter_service_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="status",
            field=models.CharField(default="Não Iniciado", max_length=40),
        ),
        migrations.AlterField(
            model_name="member",
            name="role",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="member",
            name="sector",
            field=models.CharField(max_length=20),
        ),
    ]
