# Generated by Django 4.2.7 on 2024-06-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0009_service_status_alter_member_role_alter_member_sector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="sector",
            field=models.CharField(
                choices=[
                    ("Tecnologia", "Tecnologia"),
                    ("Civil", "Construção Civil"),
                    ("Consultoria", "Consultoria"),
                    ("Gestão de Pessoas", "Gestão de Pessoas"),
                    ("Comercial", "Comercial"),
                ],
                max_length=40,
            ),
        ),
    ]
