# Generated by Django 4.2.7 on 2024-01-07 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_systemuser_role_alter_systemuser_sector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemuser',
            old_name='name',
            new_name='full_name',
        ),
    ]
