# Generated by Django 4.2.5 on 2023-10-10 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMediaMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.date)),
                (
                    "network",
                    models.CharField(
                        choices=[
                            ("IG", "Instagram"),
                            ("LI", "LinkedIn"),
                            ("FC", "Facebook"),
                            ("TK", "TikTok"),
                        ],
                        max_length=2,
                    ),
                ),
                ("followers", models.IntegerField()),
                ("impressions", models.IntegerField()),
                ("reach", models.IntegerField()),
                ("engagement", models.IntegerField()),
                ("visits", models.IntegerField()),
                ("notes", models.CharField(max_length=100)),
            ],
        ),
    ]
