# Generated by Django 4.2.5 on 2023-10-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_socialmediametric"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmediametric",
            name="date",
            field=models.DateField(),
        ),
    ]
