# Generated by Django 4.2.5 on 2023-11-12 02:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_alter_socialmediametric_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignMetric",
            fields=[
                (
                    "date",
                    models.DateField(
                        default=datetime.datetime.now, primary_key=True, serialize=False
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("GOOGLEADS", "Google Ads"),
                            ("FBADS", "Facebook Ads"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "campaign_sector",
                    models.CharField(
                        choices=[("TEC", "Tecnologia"), ("CIV", "Construção Civil")],
                        max_length=3,
                    ),
                ),
                (
                    "funnel_position",
                    models.CharField(
                        choices=[
                            ("TOPO", "Topo de Funil"),
                            ("MEIO", "Meio de Funil"),
                            ("FUNDO", "Fundo de Funil"),
                        ],
                        max_length=5,
                    ),
                ),
                ("weekly_cost", models.FloatField()),
                ("notes", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        choices=[("TEC", "Tecnologia"), ("CIV", "Construção Civil")],
                        max_length=3,
                    ),
                ),
                ("total_value", models.FloatField()),
                ("n_of_services", models.PositiveSmallIntegerField()),
                ("date", models.DateField()),
                ("link_of_contract", models.CharField(max_length=150)),
                ("notes", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                (
                    "sector",
                    models.CharField(
                        choices=[("TEC", "Tecnologia"), ("CIV", "Construção Civil")],
                        max_length=3,
                    ),
                ),
                ("email", models.CharField(max_length=80)),
                ("phone", models.CharField(max_length=16)),
                ("cpf", models.CharField(max_length=14)),
                ("degree", models.CharField(max_length=40)),
                ("date_of_birth", models.DateField()),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ASS", "Assessor(a)"),
                            ("CON", "Consultor(a)"),
                            ("GER", "Gerente"),
                            ("DIR", "Diretor"),
                            ("PRE", "Presidente"),
                        ],
                        max_length=3,
                    ),
                ),
                ("date_of_entry", models.DateField()),
                ("date_of_leave", models.DateField()),
                ("notes", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="socialmediametric",
            name="id",
        ),
        migrations.AddField(
            model_name="client",
            name="birth_date",
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="client",
            name="cpf",
            field=models.CharField(default="123-456-789-12", max_length=14),
        ),
        migrations.AddField(
            model_name="client",
            name="education",
            field=models.CharField(
                choices=[
                    ("EF-COMPLETO", "Ensino Fundamental Completo"),
                    ("EM-INCOMPLETO", "Ensino Médio Incompleto"),
                    ("ES-INCOMPLETO", "Ensino Superior Incompleto"),
                    ("ES-COMPLETO", "Ensino Superior Completo"),
                ],
                default="ES-COMPLETO",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="email",
            field=models.CharField(default="", max_length=80),
        ),
        migrations.AddField(
            model_name="client",
            name="funnel_time",
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name="client",
            name="marital_status",
            field=models.CharField(
                choices=[
                    ("SOLTEIRO", "Solteiro(a)"),
                    ("CASADO", "Casado(a)"),
                    ("DIVORCIADO", "Divorciado(a)"),
                    ("VIÚVO", "Viúvo(a)"),
                    ("UNIÃO ESTÁVEL", "União Estável"),
                ],
                default="SOLTEIRO",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="monthly_income",
            field=models.CharField(
                choices=[
                    ("1", "Até 1 salário mínimo"),
                    ("1,5", "Até 1,5 salários mínimos"),
                    ("6,5", "Até 6,5 salários mínimos"),
                    ("9", "Até 9 salários mínimos"),
                    ("+9", "Acima de 9 salários mínimos"),
                ],
                default="6,5",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="notes",
            field=models.CharField(default="Nada", max_length=100),
        ),
        migrations.AddField(
            model_name="client",
            name="phone",
            field=models.CharField(default="", max_length=16),
        ),
        migrations.AddField(
            model_name="client",
            name="profession",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="client",
            name="source",
            field=models.CharField(
                choices=[
                    ("INDICAÇÃO", "Indicação"),
                    ("FBADS", "Facebook Ads"),
                    ("GOOGLEADS", "Google Ads"),
                    ("ATIVA", "Prospecção Ativa"),
                    ("PASSIVA", "Prospecção Passiva"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="first_name",
            field=models.CharField(default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="client",
            name="gender",
            field=models.CharField(
                choices=[("M", "Homem"), ("F", "Mulher")], default="", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="last_name",
            field=models.CharField(default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="socialmediametric",
            name="date",
            field=models.DateField(
                default=datetime.datetime.now, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="socialmediametric",
            name="engagement",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="socialmediametric",
            name="followers",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="socialmediametric",
            name="impressions",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="socialmediametric",
            name="reach",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="socialmediametric",
            name="visits",
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project",
                    models.CharField(
                        choices=[
                            ("Sistema", "Sistema Web"),
                            ("Website", "Website"),
                            ("Aplicativo", "Aplicativo"),
                            ("Landing Page", "Landing Page"),
                            ("Protótipo", "Protótipo"),
                            ("E-Commerce", "E-Commerce"),
                            ("Arquitetônico", "Proj. Arquitetônico"),
                            ("Hidrossanitário", "Proj. Hidrossanitário"),
                            ("Elétrico", "Proj. Elétrico"),
                            ("Captação", "Proj. de Captação"),
                            ("Incêndio", "Proj. de Combate à Incêndio"),
                        ],
                        max_length=18,
                    ),
                ),
                ("estimated_time", models.PositiveSmallIntegerField()),
                ("actual_time", models.PositiveSmallIntegerField()),
                ("n_of_consultants", models.PositiveSmallIntegerField()),
                ("price", models.FloatField()),
                ("notes", models.CharField()),
                (
                    "contract_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.contract",
                    ),
                ),
                (
                    "member_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.member",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contract",
            name="client_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.client"
            ),
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=80)),
                ("cnpj", models.CharField(max_length=18)),
                ("field_of_action", models.CharField(max_length=100)),
                ("annual_revenue", models.FloatField()),
                ("n_of_locations", models.PositiveSmallIntegerField()),
                ("n_of_employees", models.PositiveSmallIntegerField()),
                ("proof_of_registration_link", models.CharField(max_length=150)),
                ("notes", models.CharField(max_length=100)),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.client",
                    ),
                ),
            ],
        ),
    ]
