# Generated by Django 4.2.5 on 2023-11-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_campaignmetric_contract_member_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="role",
            field=models.CharField(
                choices=[
                    ("ASS", "Assessor(a)"),
                    ("CON", "Consultor(a)"),
                    ("GER", "Gerente"),
                    ("DIR", "Diretor(a)"),
                    ("PRE", "Presidente"),
                ],
                max_length=3,
            ),
        ),
    ]
