# Generated by Django 4.2.5 on 2023-11-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_alter_member_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="score",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D"), ("E", "E")],
                default="A",
            ),
        ),
    ]
