# Generated by Django 4.2.5 on 2023-11-12 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0006_client_score"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="client_id",
            new_name="client",
        ),
        migrations.RenameField(
            model_name="contract",
            old_name="client_id",
            new_name="client",
        ),
        migrations.RenameField(
            model_name="service",
            old_name="contract_id",
            new_name="contract",
        ),
        migrations.RenameField(
            model_name="service",
            old_name="member_id",
            new_name="member",
        ),
        migrations.AddField(
            model_name="service",
            name="client",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.client",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="date_of_leave",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="sector",
            field=models.CharField(
                choices=[
                    ("TEC", "Tecnologia"),
                    ("CIV", "Construção Civil"),
                    ("COM", "Comercial"),
                    ("RH", "Recursos Humanos"),
                    ("ADM", "Adiminstrativo Financeiro"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="notes",
            field=models.CharField(max_length=100),
        ),
    ]
