# Generated by Django 4.2.7 on 2023-12-01 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_rename_client_company_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=32)),
                ('last_name', models.CharField(default='', max_length=32)),
                ('gender', models.CharField(choices=[('M', 'Homem'), ('F', 'Mulher')], default='', max_length=1)),
                ('status', models.CharField(choices=[('PRÉ-DIAGNÓSTICO', 'Pré-Diagnóstico'), ('PERDIDO PRÉ-DIAG', 'Perdido Pré-Diagnóstico'), ('PRÉ-PROPOSTA', 'Pré-Proposta'), ('PERDIDO PRÉ-PROP', 'Perdido Pré-Proposta'), ('PÓS-PROPOSTA', 'Pós-Proposta'), ('PERDIDO PÓS-PROP', 'Perdido Pós-Proposta'), ('CONTRATO FECHADO', 'Contrato Fechado')], default='PRÉ-DIAGNÓSTICO', max_length=20)),
                ('source', models.CharField(choices=[('INDICAÇÃO', 'Indicação'), ('FBADS', 'Facebook Ads'), ('GOOGLEADS', 'Google Ads'), ('ATIVA', 'Prospecção Ativa'), ('PASSIVA', 'Prospecção Passiva')], default='', max_length=10)),
                ('email', models.CharField(default='', max_length=80)),
                ('phone', models.CharField(default='', max_length=16)),
                ('field_of_action', models.CharField(default='', max_length=30)),
                ('date', models.DateField()),
                ('notes', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='client',
            name='source',
        ),
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='client',
            name='funnel_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='lead_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.lead'),
        ),
    ]
