# Generated by Django 4.2.7 on 2023-12-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_lead_remove_client_email_remove_client_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignmetric',
            name='campaign_sector',
            field=models.CharField(choices=[('TEC', 'Tecnologia'), ('CIV', 'Construção Civil'), ('CON', 'Consultoria')], max_length=3),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sector',
            field=models.CharField(choices=[('TEC', 'Tecnologia'), ('CIV', 'Construção Civil'), ('CON', 'Consultoria')], max_length=3),
        ),
        migrations.AlterField(
            model_name='service',
            name='project',
            field=models.CharField(choices=[('Sistema', 'Sistema Web'), ('Website', 'Website'), ('Aplicativo', 'Aplicativo'), ('Landing Page', 'Landing Page'), ('Protótipo', 'Protótipo'), ('E-Commerce', 'E-Commerce'), ('Arquitetônico', 'Proj. Arquitetônico'), ('Hidrossanitário', 'Proj. Hidrossanitário'), ('Elétrico', 'Proj. Elétrico'), ('Captação', 'Proj. de Captação'), ('Incêndio', 'Proj. de Combate à Incêndio'), ('Mapeamento', 'Mapeamento de Processos')], max_length=18),
        ),
    ]
