# Generated by Django 4.2.7 on 2023-12-02 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_client_lead_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='lead_id',
            field=models.ForeignKey(limit_choices_to={'status': 'CONTRATO FECHADO'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.lead'),
        ),
    ]
